apiVersion: extensions/v1
kind: Ingress
metadata:
  name: api-ingress
spec:
  backend:
    serviceName: api
    servicePort: 9090

---
kind: Service
apiVersion: v1
metadata:
  name: api
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: api-port
  selector:
    name: server

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: server
spec:
  replicas: 10
  template:
    metadata:
      name: server
      labels:
        name: server
    spec:
      containers:
      - name: server
        image: eu.gcr.io/PROJECT_ID/CLUSTER_NAME-nodejs-mini-server:VERSION
        env:
        - name: NODE_ENV
          value: prod
        - name: VERSION
          value: '1'
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          name: api-port
